AWSTemplateFormatVersion: '2010-09-09'
Description: Creates AWS Resources needed for an S3 Website



Parameters:
  DomainName:
    Type: String
    Description: The domain of the website

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: 404.html
        RoutingRules:
        - RedirectRule:
            ReplaceKeyWith: index.html
          RoutingRuleCondition: 
            KeyPrefixEquals: /
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties: 
      DomainName: !Sub "*.${DomainName}"
      SubjectAlternativeNames:
      - !Ref DomainName
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        CustomErrorResponses:
        - ErrorCode: 403
          ResponsePagePath: "/index.html"
          ResponseCode: "404"
          ErrorCachingMinTTL: 300
        - ErrorCode: 404
          ResponsePagePath: "/index.html"
          ResponseCode: "404"
          ErrorCachingMinTTL: 300
        Aliases:
          - !Ref DomainName
          - !Sub "www.${DomainName}"
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultCacheBehavior:
          ViewerProtocolPolicy: "redirect-to-https"
          TargetOriginId: !Sub "${S3Bucket}-origin"
          DefaultTTL: 1800
          AllowedMethods:
          - "HEAD"
          - "GET"
          CachedMethods:
          - "HEAD"
          - "GET"
          MinTTL: 0
          Compress: true
          ForwardedValues:
            Cookies:
              Forward: none
            QueryString: false
        Origins:
          - CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols:
              - TLSv1
              - TLSv1.1
              - TLSv1.2
            DomainName: !Sub "${S3Bucket}.s3-website-${AWS::Region}.amazonaws.com"
            Id: !Sub "${S3Bucket}-origin"

  HostedZone:
    Type: "AWS::Route53::HostedZone"
    Properties:
      Name: !Ref DomainName
      HostedZoneConfig:
        Comment: !Sub "Hosted zone for the website ${DomainName}."

  RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Type: "A"
      Name: !Sub "${DomainName}."
      HostedZoneId: !Ref HostedZone
      AliasTarget:
        DNSName: !Sub "${Distribution.DomainName}."
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2

  WwwRecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      Type: "CNAME"
      Name: !Sub "www.${DomainName}."
      TTL: 300
      ResourceRecords:
      - !GetAtt Distribution.DomainName
      HostedZoneId: !Ref HostedZone

Outputs:
  CertificateArn:
    Value: !Ref Certificate
  DistributionId:
    Value: !Ref Distribution
  DistributionDomainName:
    Value: !GetAtt Distribution.DomainName